version: 0.0
os: linux
files:
    - source: /codedeploy/app.tgz
      destination: /home/api
    - source: /codedeploy/branch.txt
      destination: /home/api
hooks:
  BeforeInstall:
    - location: codedeploy/scripts/before-install.sh
  AfterInstall:
    - location: codedeploy/scripts/after-install.sh
      runas: root
  ApplicationStart:
    - location: codedeploy/scripts/application-start.sh
      runas: root
  ApplicationStop:
    - location: codedeploy/scripts/application-stop.sh
      runas: root
  ValidateService:
    - location: codedeploy/scripts/validate-service.sh
      runas: root
      timeout: 3600